name: Reusable Node.js Setup

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: '20'
      install-deps:
        required: false
        type: boolean
        default: true
      cache-key:
        required: false
        type: string
        default: ''

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
            .next/cache
          key: ${{ inputs.cache-key || format('{0}-node-{1}', runner.os, hashFiles('**/package-lock.json')) }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        if: ${{ inputs.install-deps }}
        run: npm ci --prefer-offline --no-audit

      - name: Verify installation
        run: |
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          echo "Dependencies installed successfully"